language: ruby
sudo: false

rvm:
  - 2.4.2
addons:
  postgresql: '9.6'

before_script:
- psql -c 'create database demo_test;' -U postgres

deploy: 
  provider: heroku
  app: gem-rails-ohmy
  api_key: $HEROKU_AUTH_TOKEN

before_install:
  - gem install rubygems-update -v 3.4.22
  - gem update --system
  - gem install bundler

install: bundle install --retry=3

