default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: demo_dev

test:
  <<: *default
  database: demo_test
  username: <%= ENV['DB_USERNAME'] %>

staging:
  <<: *default
  database: demo_staging

# use embedded ruby env vars for prod
production:
  <<: *default
  database: demo_prod
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>